In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

# One dimension arrays

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [9]:
a[2]
a[2] = 10
a

array([ 1,  2, 10,  5,  7, 12])

In [10]:
np.arange(2,10)  #last number not inclusive

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [12]:
np.linspace(0,100,11) #to create an array from numbers 0 to 1

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimentional arrays

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
#This creates a two dimension array from a list of lists
n = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
n[1][2]

np.int64(6)

In [16]:
n[1][2] = 10
n

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 7,  8,  9]])

In [17]:
n[2]

array([7, 8, 9])

In [18]:
n[2] = [1,1,1]  #to change a row
n

array([[ 1,  2,  3],
       [ 4,  5, 10],
       [ 1,  1,  1]])

In [19]:
n[:,2] = [0,1,2] # to  change a column
n

array([[1, 2, 0],
       [4, 5, 1],
       [1, 1, 2]])

# Randomly Generated Arrays

In [25]:
np.random.seed(2)  #this are not totally random, they are pseudorandom
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [24]:
np.random.seed(2)  #random normal distribution
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [23]:
np.random.seed(2)  
np.random.randint(low=0,high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element wise operations

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [36]:
a + 1 # adds 1 to every elemnt of the array
a * 2

array([0, 2, 4, 6, 8])

In [37]:
b = 10 + ( a * 2) ** 2

In [38]:
a + b

array([10, 15, 28, 49, 78])

# Comparison operations

In [39]:
a >= 2 

array([False, False,  True,  True,  True])

In [40]:
b 

array([10, 14, 26, 46, 74])

In [41]:
a > b

array([False, False, False, False, False])

In [43]:
a[ a < b]   # returns the elements of a where the condition is true

array([0, 1, 2, 3, 4])

# Summarizing operations

instead of returning an array, they return a single number

In [44]:
a.min()

np.int64(0)

In [45]:
a.sum()

np.int64(10)

In [46]:
a.mean()

np.float64(2.0)

In [47]:
a.std()

np.float64(1.4142135623730951)

In [48]:
n.sum()

np.int64(17)