# Linear algebra refresher
Vector operations : are normally the columns in a matriz

In [1]:
import numpy as np

In [2]:
u = np.array([2,4,5,6])

In [3]:
2*u

array([ 4,  8, 10, 12])

In [4]:
v= np.array([1,0,0,2])

In [5]:
u + v

array([3, 4, 5, 8])

In [6]:
u * v

array([ 2,  0,  0, 12])

### Vector vector multiplication (dot product)

If we have a row vector multiplied a column vector, we need to do a traspose of row vector

In [8]:
#vector multiplication in a function

def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]  # the vectors need to be of same size

    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

vector_vector_multiplication(u,v)

np.float64(14.0)

In [9]:
u.dot(v)

np.int64(14)

### Matrix-vector multiplication

Uxv the number of columns in U should match the number of rows in v

In [10]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [12]:
def matrix_vector_multipliation( U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)

    return result   

matrix_vector_multipliation()

array([14.,  5.,  5.])

In [ ]:
U.dot(v)

### Matrix matrix multiplication UV
is a matrix -vector multiplication for each column

In [20]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows,num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multipliation(U,vi)
        result[:, i] = Uvi

    return result

In [21]:
V = np.array([
    [1, 1, 2],
    [0, 0.5,1], 
    [0, 2,1],
    [2,1,0]
])

matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [22]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix (I)
Square matrix where the diagonal is 1.
When you multiply any U matrix by the I you get U.
It is like the number 1 for matrix.

In [27]:
I = np.eye(3)

In [25]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [28]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Inverse

In [29]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [30]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [31]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])